Task 12
Minneapolis-7/game pull request #14
Opened 2021-08-11 18:46 UTC by DariaZherebtsova

Посмотрите правильной ли я дорожкой иду, и нужно ли делать контроллеры как в первом модуле были?

2021-08-11 19:51 UTC, andreyvolokitin approved these changes

2021-08-11 19:51 UTC, andreyvolokitin commented on src/api/api.ts
> +  const instance = axios.create({
Можно было бы сразу возвращать без присвоения

2021-08-11 19:51 UTC, andreyvolokitin commented on src/api/auth-api.ts
> +  signin(user: SignInRequest): Promise<AxiosResponse<any>> {
Ответ сервера тут имеет значение? Я в прошлом модуле ничего не возвращал из `signin()` (т.е. тип возврата был `Promise<void>`), заодно и `any` избежал

2021-08-11 19:51 UTC, andreyvolokitin commented on src/api/types.ts
> +};
Здесь описывалась концепция "DTO"-объектов (с 1:43:10): https://disk.yandex.ru/i/OxpCdqyHrLHyTA , считаю можно её рассмотреть для применения. И там же дальше говорят про трансформацию данных с серверного формата в клиентский (в основном это конвертация snake_case в camelCase и обратно, в 1 модуле вроде даже многие писали такую функцию по трансформации). Это же относится к коду в `index.tsx`, где на сервер отправляются данные тестового юзера

2021-08-11 20:28 UTC, andreyvolokitin commented on src/api/auth-api.ts
> +  signin(user: SignInRequest): Promise<AxiosResponse<any>> {
Хотя я это делал через `async/await`, так что тут это не подойдёт (вообще в идеале было бы круто использовать `async/await` вместо обычных промисов). Но суть в том что нас не интересуют возвращаемые данные при успешном запросе, т.е. можно было бы их не учитывать и не типизировать, и избежать `any`, но с обычными промисами это сложнее. С `async/await` было бы так:

```
// async-функция всегда возвращает промис, потому `Promise<void>`
async signin(user: SignInRequest): Promise<void> {
	await auth.post('/signin', user);
}

// использование
try {
	await API.signin(user);

	// код для успешного логина
} catch(e) {
	// ошибка логина
}
```

2021-08-12 06:06 UTC, DariaZherebtsova commented on src/api/api.ts
> +  const instance = axios.create({
если сразу возвращать eslint ругается https://eslint.org/docs/rules/no-return-assign

2021-08-12 07:52 UTC, DariaZherebtsova commented on src/api/types.ts
> +};
@mukhindev, @kotosha-real что вы думаете про трансформацию данных с серверного формата в клиентский?

2021-08-12 07:58 UTC, DariaZherebtsova commented on src/api/auth-api.ts
> +  signin(user: SignInRequest): Promise<AxiosResponse<any>> {
перешла на async/await

2021-08-12 11:36 UTC, andreyvolokitin commented on src/api/api.ts
> +  const instance = axios.create({
Хм, странно, у меня не выдаёт ошибку: https://i.imgur.com/jPtt4kF.png

Впрочем, это не особо важно (но ассайнмента там вроде бы нету)

2021-08-12 12:14 UTC, mukhindev commented on src/api/types.ts
> +};
> в 1 модуле вроде даже многие писали такую функцию по трансформации
Я дедал как раз так. Но без глубокой трансформации, чисто первый уровень. Его хватало, а дальше развить не успел
https://github.com/mukhindev/middle.messenger.praktikum.yandex/blob/main/src/utils/keysConverter.ts

2021-08-13 12:31 UTC, DariaZherebtsova commented
применила концепцию "DTO"-объектов

2021-08-13 17:03 UTC, mukhindev commented on src/api/api.ts
> +  const instance = axios.create({
У меня тоже **не** ругается если сразу вернуть

2021-08-13 17:19 UTC, mukhindev approved these changes
Принято 👍
Про контроллеры мне кажется станет понятнее когда до Redux дойдём.

Единственный момент, думаю стоит выбрать функциональные или классовые писать компоненты. Вроде как много новых библиотек ориентируются именно на функциональные и хуки. Даже удивило что в теории к спринту почему-то больше классам уделено внимания.

В документации React даже есть рекомендация (но не принуждение): https://ru.reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both

2021-08-13 17:33 UTC, andreyvolokitin commented
> стоит выбрать функциональные или классовые писать компоненты

Конечно функциональные, классы только там где без них не обойтись

2021-08-14 15:20 UTC, kotosha-real requested changes
Хорошая работа!
Я оставил комменты, их немного, но некоторые из них важные. После того, как поправишь, я ещё раз посмотрю

2021-08-14 15:20 UTC, kotosha-real commented on src/api/auth-api.ts
> +    return response.data.id;
❗️
А вот возвращаемое значение — нет. В аннотации функции сказано, что возвращаемый промис зарезолвит `AxiosResponse<SignUpResponse>`, а по факту, он резолвит `number`. Либо это `Promise<number>`, либо возвращать функция должна сам `response`

2021-08-14 15:20 UTC, kotosha-real commented on src/api/auth-api.ts
> +    const response = await auth.post('/signup', user);
❗️
`return`-ы стоит отбивать пустой строкой для лучшей читаемости
```suggestion
    const response = await auth.post('/signup', user);
    
```

2021-08-17 05:32 UTC, kotosha-real approved these changes
🕵🏻‍♂️
Есть аппрув)
Но обрати внимание на комменты, что я оставил, давай их затащим и будем мержить

2021-08-17 05:32 UTC, kotosha-real commented on src/api/test-use.tsx
> +  const [id, setId] = useState<unknown>(null);
❗️
Мы знаем, что придёт, а также сами задаём базовое значение, поэтому логично переписать так:
```suggestion
  const [id, setId] = useState<number | null>(null);
```

2021-08-17 05:32 UTC, kotosha-real commented on src/api/auth-api.ts
> +  },
❗️
Не совсем так:
```suggestion
  async signup(user: User): Promise<number> {
    const userDTO: UserDTO = transformUserToDTO(user);
    const response = await apiYandex.post<{ id: number }>('/auth/signup', userDTO);

    return response?.data?.id;
  },
```

Вот что поменялось:
1. Мы возвращаем `id`, на `response`, следовательно возвращаемый промис резолвится в `Promise<number>`, а не в `Promise<AxiosResponse<number>>`
2. Дополнительно типизируем возвращаемое значение ручки `/auth/signup` через дженерик метода `post`

2021-08-17 05:32 UTC, kotosha-real commented on src/api/auth-api.ts
> +import { transformUserToDTO } from '../utils/transformUser';
🧐
На типы и утилитиы хочется добавить алиасы

2021-08-17 09:22 UTC, DariaZherebtsova commented on src/api/auth-api.ts
> +  },
А тут не важно что id не response, а в response.data?

2021-08-17 09:53 UTC, kotosha-real commented on src/api/auth-api.ts
> +  },
Это ок, потому что этот дженерик типизирует именно `data`. В этом можно убедиться, провалившись в определение `AxiosResponse` в `index.d.ts` файле либы

2021-08-17 10:14 UTC, merged