Cоздать прототип с базовыми механиками игры
Minneapolis-7/game pull request #15
Opened 2021-08-12 19:27 UTC by mukhindev

Чтобы не создавать конфликтов, компонент с игрой не подключен.
Для тестирования выводите компонент `components/GameReactComponent`

2021-08-13 14:08 UTC, andreyvolokitin approved these changes
Игра отличная, код хороший, аппруваю, т.к. не вижу себя вправе задерживать ревью Антона

2021-08-13 14:08 UTC, andreyvolokitin commented on src/game/types.ts
> +};
В продолжении о коллизиях, эта штука скорей — `(Player)BoundingBox`, т.е. пространство которое занимает сущность

2021-08-13 14:08 UTC, andreyvolokitin commented on src/game/utils/constants.ts
> +  LEFT: [64, 0],
Не понятна суть названий, но думаю это просто потому что я не достаточно понял код. Возникающие вопросы, когда смотришь код с наскоку: 
- что такое `STAY`?
- почему по оси X задано два свойства (`RIGHT` и `LEFT`), а по оси Y — ни одного?

2021-08-13 14:14 UTC, mukhindev commented on src/components/GameReactComponent/GameReactComponent.tsx
> +import { GameState } from '../../game/types';
WebStorm мне как раз упорно предлагал game/classes)

2021-08-13 14:16 UTC, mukhindev commented on src/components/GameReactComponent/GameReactComponent.tsx
> +    const gameReactComponent = new Game({
Да, конечно)) Спасибо что заметил. Если честно не помню чтобы так называл эту const. Файл несколько раз переименовавал, может авторефакторинг так решил.

2021-08-13 14:23 UTC, mukhindev commented on src/components/GameReactComponent/GameReactComponent.tsx
> +      onGameStateUpdate: (newGameState: GameState) => {
Я долго крутился вокруг этого) Сокращу до `onStateUpdate`.
До `onUpdate` не хотелось сокращать из-за того что под обновлением игры понимаю вообще любые обновления в нет.

2021-08-13 14:23 UTC, mukhindev commented on src/components/GameReactComponent/GameReactComponent.tsx
> +const GameReactComponent: React.FC<GameProps> = ({ startLevelIndex = 0 }) => {
Посмотрю, спасибо

2021-08-13 14:27 UTC, mukhindev commented on src/game/classes/Control.ts
> +    document.addEventListener('keyup', (evt) => {
Более того, я это даже хотел. Забыл)
Не знаю как будет дальше, но сейчас игра создаётся непосредственно в компоненте. Поэтому да, лучше удалять.

2021-08-13 14:28 UTC, mukhindev commented on src/game/classes/Control.ts
> +    Object.entries(this.registeredKeys).forEach(([key, value]) => {
Можно) Тут вообще изначально `for in` был, но он не понравился ESLint

2021-08-13 14:31 UTC, mukhindev commented on src/game/classes/Game.ts
> +    } = options;
Это да. Если честно специально так делаю, мне почему-то визуально так приянее)

2021-08-13 14:34 UTC, mukhindev commented on src/game/classes/Game.ts
> +      1: { sprite: [480, 0], isUseCollision: true },
Написал c `is`, так как в контексте React `use` ассоциируют с хуками.
Интересно мнение @kotosha-real и @DariaZherebtsova

2021-08-13 14:43 UTC, mukhindev commented on src/game/classes/Game.ts
> +    this.objects = {
Ну принципиально мне кажется ничего не изменится. Только появится строгий порядок и считать какой элемент по порядку придётся, если не осталять комментарии.
Также есть идея для более удобного описания уровней использовать не просто цифры, а разбить на групы. Например `a1`, `a2`, `a3`, всё что на `a` — это стены и тд. А для хорошо выглядещей игры придётся разнообразие в блоках вводить.

2021-08-13 14:44 UTC, mukhindev commented on src/game/classes/Game.ts
> +          if (player.velocityX > 0) {
Лично я сам иногда отдея `if`, так что против не буду. Можно добавить правило, если @DariaZherebtsova не против.

2021-08-13 14:49 UTC, mukhindev commented on src/game/classes/GameObject.ts
> +  id?: number;
Не может. Спешил и не разделил типы. Там тип `GameObjectConstructorOptions` используется и в конструкторе и в `this.objects` в `Game`.
Хотя я подумал, может и правда сделать `this.objects` массивом и использовать поле `id`?, а где-то при подготовке уровня просто превращать массив и объект.

2021-08-13 14:55 UTC, mukhindev commented on src/game/classes/Game.ts
> +      isDoorUnlock: false,
Согласен

2021-08-13 14:55 UTC, mukhindev commented on src/game/classes/Player.ts
> +  public isJump: boolean;
И тут соглашусь)

2021-08-13 14:55 UTC, andreyvolokitin commented on src/game/classes/Game.ts
> +    this.objects = {
> Только появится строгий порядок и считать какой элемент по порядку придётся, если не осталять комментарии.

Комментарии по-моему в любом случае нужны, просто будут перед каждым элементом массива стоять

Почему я про массив заговорил: ключи у этого объекта — как индексы у массива, без пропусков, начиная 0, т.е. с первого взгляда кажется, что замена на массив логична. Но я многого не знаю и возможно массив не оправдан. Если ключи объекта потенциально могут стать не как индексы у массива, то конечно лучше не менять

2021-08-13 14:56 UTC, mukhindev commented on src/game/classes/Player.ts
> +  update(world: any, control: ControlKeysState): void {
О! Спасибо! Вечером проверю

2021-08-13 14:57 UTC, andreyvolokitin commented on src/game/classes/GameObject.ts
> +  id?: number;
Вопрос исключительно о `?` после `id`, т.е. сразу говорит, что `id` якобы опционален

2021-08-13 14:58 UTC, mukhindev commented on src/game/classes/View.ts
> +    canvas.height = CANVAS_SIZE_Y;
Спасибо! 
А про ресайз на следующий спринт уже)

2021-08-13 15:15 UTC, mukhindev commented on src/game/utils/constants.ts
> +  LEFT: [64, 0],
Это координаты спрайта персонажа в `px` на `sprites.png` (левой верхней точки) для разных его состояний:
STAY — когда не двигается
RIGHT — движется вправо
LEFT — движется влево

У меня с английским не очень, есть более подходящее слово?

2021-08-13 15:17 UTC, mukhindev commented on src/game/types.ts
> +};
Возможно так правильнее

2021-08-13 15:20 UTC, mukhindev commented on src/game/classes/World.ts
> +    this.player.setCollision(collision);
Как я говорил, это было решение в лоб) Не факт что останется именно в таком виде. Я собираюсь делее более детально изучить вопрос — а как это делают на самом деле.

2021-08-13 15:23 UTC, andreyvolokitin commented on src/game/utils/constants.ts
> +  LEFT: [64, 0],
```
export const PLAYER_SPRITE_COORDS: Record<string, XYCoordinates> = {
  STATIONARY: [0, 0],
  MOVING_RIGHT: [32, 0],
  MOVING_LEFT: [64, 0],
};
```

2021-08-13 15:36 UTC, mukhindev commented on src/components/GameReactComponent/GameReactComponent.tsx
> +import { SPRITES_FILE } from '../../game/utils/constants';
А это привычка с Практикума первого этажа, там нас просили в utils класть и константы. Хотя `shared` мне кажется ближе по смыслу. Перемещу в `shared`

2021-08-13 18:06 UTC, DariaZherebtsova approved these changes

2021-08-13 18:17 UTC, DariaZherebtsova commented on src/game/classes/Game.ts
> +      1: { sprite: [480, 0], isUseCollision: true },
может makeCollision

2021-08-13 18:18 UTC, DariaZherebtsova commented on src/game/classes/Game.ts
> +          if (player.velocityX > 0) {
я за пустые строки

2021-08-14 07:41 UTC, mukhindev commented on src/game/classes/View.ts
> +        this.ctx?.drawImage(
Хотя в `if` явно будет `return` при `null`, TS внутри forEach всё равно ругается на `Object is possibly 'null'.` и нужны дополнительные проверки.

2021-08-14 08:46 UTC, mukhindev commented on src/game/classes/Game.ts
> +    this.objects = {
Поменял всё-таки на массив)

2021-08-14 08:48 UTC, mukhindev commented on src/game/classes/Game.ts
> +      1: { sprite: [480, 0], isUseCollision: true },
Решил сделать `hasCollision`.
`makeCollision` больше для названия метода.
А `useCollision` как говорю смущает с ассоциацией с хуками.

2021-08-14 08:50 UTC, mukhindev commented on src/game/classes/Game.ts
> +          if (player.velocityX > 0) {
Отделил

2021-08-14 15:31 UTC, kotosha-real commented on src/game/classes/Game.ts
> +    const levelObjects = this.buildLevelObjects(this.levels[this.startLevelIndex]);
Плюсую, хотя, всё, что касается стайл-гайда довольно опциональное

2021-08-14 15:34 UTC, kotosha-real commented on src/game/classes/World.ts
> +    this.player.setCollision(collision);
Тут больше про нейминг, это что-то в духе хитбокса получается

2021-08-15 10:09 UTC, kotosha-real requested changes
Отличная работа!
По итогам спринта у нас есть почти готовая игра, которую дальше нужно улучшать, а не доделывать, и это очень круто!
Я оставил комменты, некоторые из них нужно поправить, по остальным подумать/обсудить

2021-08-15 10:09 UTC, kotosha-real commented on src/game/classes/View.ts
> +          );
❗️
Давай это вынесем в отдельную функцию `drawDebugCollisionBox` (или как-то так)

2021-08-15 10:09 UTC, kotosha-real commented on src/game/classes/World.ts
> +    this.resetToDefault();
❗️
Кажется, @andreyvolokitin где-то выше говорил, что блоки констант/переменных стоит отделять пустой строкой. Это хорошая практика для повышения читаемости, можно использовать в любом кейсе

2021-08-15 10:09 UTC, kotosha-real commented on src/game/types.ts
> +};
`PlayerHitBox`. Это хорошее устоявшееся название

2021-08-15 10:09 UTC, kotosha-real commented on src/game/shared/constants.ts
> +} as const;
❓
Зачем `as const`?

2021-08-15 10:09 UTC, kotosha-real commented on src/game/classes/Game.ts
> +  setGameState<T extends keyof GameState, K extends GameState[T]>(key: T, value: K): void {
🧐
Здесь хорошие тайпинги, но вызов `setGameState` с руками введённым ключом — это не очень удобно. Было бы круто использовать так:
```
setGameState(GameStateKeys.someKey, value)
```

2021-08-15 12:21 UTC, mukhindev commented on src/game/classes/Game.ts
> +    this.updateGameState(this.gameState);
Шикарно! Спасибо)

2021-08-15 13:01 UTC, mukhindev commented on src/game/shared/constants.ts
> +} as const;
Свойства объекта станут `read-only`. Чтобы нельзя было далее в коде переопредилить так: `CONTROL_KEY.LEFT = 'down';`

2021-08-15 13:32 UTC, mukhindev commented on src/game/classes/Game.ts
> +  setGameState<T extends keyof GameState, K extends GameState[T]>(key: T, value: K): void {
Завёл константы

2021-08-15 13:38 UTC, mukhindev commented on src/game/classes/Game.ts
> +    this.updateGameState(this.gameState);
Исправил

2021-08-15 13:38 UTC, mukhindev commented on src/components/GameReactComponent/GameReactComponent.tsx
> +}
Убрал

2021-08-15 13:39 UTC, mukhindev commented on src/components/GameReactComponent/GameReactComponent.tsx
> +      view: new View(gameCanvasRef.current, sprite),
Согласен

2021-08-15 13:48 UTC, mukhindev commented on src/components/GameReactComponent/GameReactComponent.tsx
> +import Control from '../../game/classes/Control';
Согласен

2021-08-15 13:50 UTC, mukhindev commented on src/game/classes/Control.ts
> +  }
Хорошо

2021-08-15 13:56 UTC, mukhindev commented on src/game/classes/GameObject.ts
> +  z?: number;
Не успел реализовать, зарезервировал. Это как z-index, чтобы блоки можно было рисовать перед игроком. Например для воды понадобится или леса какого нибудь.
Идея была такая 0 за играком, 1 перед ним.

2021-08-15 13:57 UTC, mukhindev commented on src/game/classes/Control.ts
> +    this.registeredKeys = {};
Буду иметь ввиду

2021-08-15 13:58 UTC, mukhindev commented on src/game/classes/Game.ts
> +    this.control.addKey('KeyT', CONTROL_KEY.T);
Вынес

2021-08-15 14:09 UTC, mukhindev commented on src/game/classes/Game.ts
> +        onOver: ({ object }) => {
Согласей, заменил

2021-08-15 14:24 UTC, mukhindev commented on src/components/GameReactComponent/GameReactComponent.tsx
> +import { GameState } from '../../game/types';
Подтянул текущий `dev`, а то тут eslint ругался и переписал все пути начиная с `game/`

2021-08-15 14:31 UTC, kotosha-real commented on src/game/classes/Control.ts
> +    this.registeredKeys = {};
Тут чуть наврал, это TS, но в целом — да, бывает удобно)

2021-08-15 14:37 UTC, kotosha-real approved these changes
🕵🏻‍♂️
Повторюсь ещё раз — отличная работа)
Аппрувлю, оставил ещё один коммент — если посчитаешь логичным, то добей ещё его и можно мёржить

2021-08-15 14:37 UTC, kotosha-real commented on src/game/entities/View.ts
> +        this.renderDebugLevelTiles(gameObject, colIndex, rowIndex, control);
🧐
Давай оставим условие тут, и если `T` нажата, то рисуем дебаг-тайлы. Либо вообще вынесем вывод дебаг-тайлов в функцию `update` — кажется, что там это будет логичнее

2021-08-15 15:25 UTC, mukhindev commented on src/game/entities/View.ts
> +        this.renderDebugLevelTiles(gameObject, colIndex, rowIndex, control);
В update логично, но не хочется ещё раз бежать по двумерному массиву) Оставил условие.

2021-08-15 15:26 UTC, merged