Task 94
Minneapolis-7/game pull request #96
Opened 2021-09-09 12:47 UTC by DariaZherebtsova

есть несколько вопросов, напишу их ниже, потому что предыдущий опыт показал, что вопросы в описании пр вы не читаете)

2021-09-09 12:58 UTC, DariaZherebtsova commented on src/pages/LoginPage/LoginPage.tsx
> +import { ToastItem } from '@/components/ui/Toast/Toast';
Где хранить типы для компонентов? Импортировать из index?

2021-09-09 13:02 UTC, DariaZherebtsova commented on src/components/ui/Toast/Toast.tsx
> +    toastList.splice(toastListItem, 1);
Так можно делать? Здесь же меняется props

2021-09-09 13:04 UTC, DariaZherebtsova commented on src/components/ui/Toast/toast.scss
> +  top: 12px;
Если у нас есть штука, которая автоматически переводит px в rem, я могу оставить тут px? или лучше перевести в rem

2021-09-09 13:07 UTC, DariaZherebtsova commented on src/pages/LoginPage/LoginPage.tsx
> +      setList([...list, toastProperties]);
Почему-то добавляется только один toast, помогите разобраться

2021-09-10 07:26 UTC, DariaZherebtsova commented on src/pages/LoginPage/LoginPage.tsx
> +        description: err.message,
С этим разобралась - https://redux-toolkit.js.org/api/createAsyncThunk#handling-thunk-results

2021-09-10 09:51 UTC, andreyvolokitin approved these changes

2021-09-10 09:51 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +  animation: toast-in-right 0.7s;
Тут надо использовать `transition`, без `animation`. transition — для анимированного перехода из css-значения (transform) в другое.  animation уже для описания более сложных анимаций, тут он не нужен, и тем более не вместе с transition

Также для оптимизации рендеринга браузером нужно добавлять `will-change: transform` — свойство говорит браузеру что мы будем анимировать `transform`, и он делает свои оптимизации отталкиваясь от этого

2021-09-10 09:51 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +}
Позиционирование надо делать через модификатор: `.контейнер_top-left`. Анимацию тостов — через родительский селектор `.контейнер_top-left > .контейнер__item`

2021-09-10 09:51 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +  margin-bottom: 15px;
Обе записи устанавливают нижний марджин. Можно просто написать `margin-bottom: 15px;`. И всегда надо стремиться записывать максимально кратко (странно что stylelint не отлавливает это)

2021-09-10 09:51 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +  border-radius: 3px 3px 3px 3px;
`border-radius: 3px`

2021-09-10 09:51 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +  background-repeat: no-repeat;
`background-position` и `background-repeat` применяются для картинок в фоне, тут их вроде нет, т.е. надо просто писать `background: $light-color`. Если бы картинки были, то лучше было бы использовать краткую запись: `background: $light-color url('картинка') 15px 0 no-repeat;`. Краткая запись любых css-свойств используется для общего задания стилей, а запись по отдельным свойствам (как `background-position`) — для уточнений и переопределений

2021-09-10 09:51 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +  pointer-events: auto;
Это дефолтное значение для этого свойства, т.е. не нужно

2021-09-10 09:51 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +  transition: 0.3s ease;
Анимацию лучше делать в стилях контейнера, т.е. там доступно его позиционирование: `.контейнер_top-left > .контейнер__item`, ну и в целом вроде анимация появления тостов больше принадлежит к тостеру/контейнеру, чем к самому тосту

2021-09-10 09:51 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +  cursor: pointer;
`cursor: pointer;` можно ставить просто на элемент, а не на :hover, но если тост не активен для клика, т.е. ему вообще не нужен `cursor: pointer`. Для `opacity` можно было бы тоже задать `transition` для консистентности (хотя я бы вообще не трогал opacity, т.е. всегда было бы 1)

2021-09-10 09:51 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +  max-height: 100px;
Для адаптивности надо задавать `max-width: 100%`. `max-height` лучше заменить на ограничение строк в тосте (через миксин `line-clamp`). Например, для заголовка `line-clamp(1)`, для описания `line-clamp(3)`. Тогда бы и `overflow: hidden` на самом тосте стал бы не нужен

2021-09-10 09:51 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +  width: 300px;
Сам тост уже ограничен по ширине, здесь ширина не нужна

2021-09-10 09:51 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +  text-align: left;
- Высота не нужна, 
- для тайтла надо применять тег `h` а не `p`, 
- `margin: 0 0 6px`,
- `font-weight` лучше ставить через ключевые слова (`bold`) и с тегом `h` он не будет нужен,
- `text-align: left;` не нужен

2021-09-10 09:51 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +}
с миксином `line-clamp` можно здесь убрать всё, кроме `margin: 0`;

`margin-left: -1px;` — такие стили вредны, т.к. всё должно работать "само собой", без таких точечных интервенций; без крайней необходимости такое лучше не делать, иначе нужно оставлять комментарий, откуда и зачем взялось значение `-1`: https://stackoverflow.com/questions/47882/what-is-a-magic-number-and-why-is-it-bad

2021-09-10 09:51 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +}
`image` я бы вообще убрал, но для его вёрстки лучше использовать `flex` (если конечно не нужно, чтобы текст именно обтекал картинку, а у нас всего несколько строк, т.е. обтекать не будет)

2021-09-10 09:51 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +}
Это декоративная иконка, её лучше делать фоном, а не через тег `img` (он для контентных изображений). Ну и свойства `src` нет, надо делать через `background`.

2021-09-10 09:51 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +}
`.тост__close-button`

`float` для вёрстки нужно использовать только если нужно, чтобы текст вокруг картинки (или другого элемента) обходил. Здесь лучше абсолютно позиционировать кнопку (и задать паддинг тосту достаточный, чтобы кнопка вмещалась в него и не перекрывала контент)

Также надо использовать готовый компонент `Button` (с `Icon` внутри), тогда из стилей останется только спозиционировать кнопку, остальное будет не нужно

2021-09-10 10:02 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +}
Уточнение: поскольку это декоративное изображение, тут ни flex ни float не нужны. Просто `padding-left` на тосте и иконка в фоне

2021-09-10 10:14 UTC, andreyvolokitin commented on src/components/ui/Toast/Toast.tsx
> +  autoDelete: boolean;
Кстати ещё при таймауте желательно ещё сделать так, чтобы при ховере он сбрасывался. А при маусауте опять запускался с тем временем, которое оставалось до ховера, но не менее 1 секунды например. Т.к. если юзер захочет прочитать что там написано, наведёт мышку, а он скроется, будет неудобно

2021-09-10 10:15 UTC, andreyvolokitin commented on src/pages/LoginPage/LoginPage.tsx
> +      setList([...list, toastProperties]);
Этот момент должен решиться при переделывании с помощью контекста

2021-09-10 15:17 UTC, andreyvolokitin commented on src/components/ui/Toast/Toast.tsx
> +          </div>
Хотя почему не стоит. Все сообщения можно хранить. Просто у них будет разный тип — error или success, т.е. вообще не сильно усложнит

2021-09-11 10:01 UTC, kotosha-real commented on src/components/ui/Toast/toast.scss
> +  transition: transform 0.6s ease-in-out;
`0.15s`, кстати, быстровато, как по мне. Классика в `0.3s` работает почти всегда, можно как раз на тосте прочекать

2021-09-11 10:04 UTC, kotosha-real commented on src/components/ui/Toast/toast.scss
> +  animation: toast-in-right 0.7s;
> Не применяйте `will-change` к элементам для выполнения преждевременной оптимизации. Если ваша страница хорошо отрабатывается, не применяйте `will-change` свойство к элементу только чтобы выжать немного больше скорости. `will-change` предназначен для использования в крайнем случае, для того чтобы исправить существующие проблемы оптимизации. Его не следует использовать для предвидения проблем оптимизации. Чрезмерное использование `will-change` приведёт к излишнему потреблению памяти и вызовет более тяжёлый рендеринг так как браузер будет пытаться подготовиться к возможным изменениям. Это приведёт к ухудшению производительности

Это с mdn. Лучше не овер-юзать `will-change`. Понадобится — применим

2021-09-11 10:34 UTC, kotosha-real requested changes
У Андрея много комментов + я добавил предложение заюзать [react-tostify](https://fkhadra.github.io/react-toastify/introduction). Это будет проще, легче и удобнее. Сейчас тосты надо добавлять в каждый из компонентов, а также расширять эти компоненты специфичным стейтом, и делать так каждый раз — очень не хочется

2021-09-11 10:34 UTC, kotosha-real commented on src/pages/LoginPage/LoginPage.tsx
> +        <Toast toastList={list} position="bottom-right" autoDelete={true} dismissTime={5000} />
❗️
Очень не нравится везде использовать компонент тоста. Попробуй посмотреть в сторону [react-toastify](https://fkhadra.github.io/react-toastify/introduction). Там нужно будет использовать контейнер в руте и дальше декларативно вызывать его там, где нужно. Это более расширяемый и удобный подход, хочется тут увидеть то же самое. Это также уберёт почти 100% комментариев @andreyvolokitin

2021-09-11 11:17 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +  animation: toast-in-right 0.7s;
Ого, не знал, надо mdn почаще читать, последний раз когда вентилировал эту тему `will-change` типа была как "опция по умолчанию" для анимируемых элементов

2021-09-11 12:32 UTC, andreyvolokitin commented on src/pages/LoginPage/LoginPage.tsx
> +        <Toast toastList={list} position="bottom-right" autoDelete={true} dismissTime={5000} />
Может таким самим попробовать, раз уж взялись. Ну как решите

2021-09-16 08:37 UTC, DariaZherebtsova commented on src/components/ui/Toast/toast.scss
> +  animation: toast-in-right 0.7s;
без animation они не выезжают, а просто появляются

2021-09-16 08:52 UTC, andreyvolokitin commented on src/components/ui/Toast/toast.scss
> +  animation: toast-in-right 0.7s;
Чтоб transition работал, нужны 2 состояния, между которыми будет переход, для этого можно класс менять. По умолчанию (после добавления) тост скрыт (`transform: translateX(-100%)`), потом сразу добавляешь класс типа `.is-visible` с `transform: translateX(0)`, и тост выезжает (у него указано `transition: transform $transition-duration`)

2021-09-17 07:53 UTC, kotosha-real reviewed
Ещё чуть-чуть и будет аппрув!

2021-09-17 07:53 UTC, kotosha-real commented on src/components/ui/Toaster/Toaster.tsx
> +  const deleteToast = (id: number) => {
❗️
`useCallback`

2021-09-17 07:53 UTC, kotosha-real commented on src/components/ui/Toaster/Toaster.tsx
> +    const interval = setInterval(() => {
❓
А почему таймаут тут? У тебя могут быть тосты с разными таймаутами, это их проп, не всего тостера)
Точнее, он может быть у тостера, чтобы задать дефолтный таймаут, но тосты должны уметь его переопределять

2021-09-17 07:53 UTC, kotosha-real commented on src/components/ui/Toaster/Toaster.tsx
> +    const interval = setInterval(() => {
Есил учитывать это, то тосты будут удалять себя сами (внутри себя на маунт запустят таймер, и сообщат наверх об удалении, когда он истечёт. Так будет корректнее

2021-09-17 07:53 UTC, kotosha-real commented on src/index.tsx
> +  const ctx = {
❗️
```suggestion
  const [toastList, setToastList] = useState<Array<ToastItem>>([]);
  
  const ctx = {
```

2021-09-17 07:53 UTC, kotosha-real commented on src/pages/LoginPage/LoginPage.tsx
> +        id: Math.floor(Math.random() * 100 + 1),
❗️
Так делать не стоит, возможны клэши айдишников. Лучше заюзать [uuid](https://www.npmjs.com/package/uuid)

2021-09-17 12:29 UTC, DariaZherebtsova commented on src/pages/LoginPage/LoginPage.tsx
> +        id: Math.floor(Math.random() * 100 + 1),
A какую uuid функцию обычно используют v1 - timestamp или v4 - random?

2021-09-17 12:30 UTC, DariaZherebtsova commented on src/components/ui/Toaster/Toaster.tsx
> +  const deleteToast = (id: number) => {
В данном случае надо что-то в deps записывать?

2021-09-18 18:49 UTC, kotosha-real reviewed
Всё ближе, последняя итерация и будет аппрув)

2021-09-18 18:49 UTC, kotosha-real commented on src/pages/LoginPage/LoginPage.tsx
> +        id: uuidv1(),
Отвечая на твой вопрос — обычно `v4`, но не так принципиально

2021-09-18 18:49 UTC, kotosha-real commented on src/components/ui/Toaster/Toast/Toast.tsx
> +    const interval = setInterval(() => {
❗️
Лучше запускать `setTimeout` с переданным таймаутом и стопить его по ховеру, запоминая оставшееся время, чтобы по блюру запустить новый таймаут с указанным временем. Сейчас не очень понятно, зачем тут именно интервал, зачем проверка на таймаут внутри коллбэка и почему сам интервал может быть таким коротким, как `1ms`.

2021-09-18 18:49 UTC, kotosha-real commented on src/components/ui/Toaster/Toaster.tsx
> +        <Toast key={toast.id} deleteToast={deleteToast} toast={toast}></Toast>
❗️
```suggestion
        <Toast key={toast.id} deleteToast={deleteToast} toast={toast} />
```

2021-09-19 14:38 UTC, DariaZherebtsova commented on src/components/ui/Toaster/Toast/Toast.tsx
> +    const interval = setInterval(() => {
Проверка на таймаут потому что он может быть null, не знаю как лучше это сделать

2021-09-19 19:31 UTC, kotosha-real commented on src/components/ui/Toaster/Toast/Toast.tsx
> +      clearTimeout(timer as NodeJS.Timeout);
❓
`NodeJS.Timeout`?

2021-09-19 19:34 UTC, kotosha-real commented on src/components/ui/Toaster/Toast/Toast.tsx
> +      setLeftTimerTime(5000 - (performance.now() - startTimer));
❗️
Хардкода быть не должно)
```suggestion
      setLeftTimerTime(timer.timeout - (performance.now() - startTimer));
```

2021-09-19 19:40 UTC, kotosha-real commented on src/components/ui/Toaster/Toast/Toast.tsx
> +      if (toast.timeout) {
❗️
Кажется, что эта проверка должна быть выше)
А вообще не так уж она и нужна. У тоста всегда должен быть какой-то таймаут: либо свой, либо из тостера

2021-09-19 19:40 UTC, kotosha-real commented on src/components/ui/Toaster/Toast/Toast.tsx
> +    const timeout = setTimeout(() => {
❗️
```suggestion
    setStartTimer(performance.now());
    
    const timeout = setTimeout(() => {
```

2021-09-19 19:41 UTC, kotosha-real commented on src/components/ui/Toaster/Toast/Toast.tsx
> +    }, toast.timeout || 1);
❗️
Давай избавимся от фоллбэка до единички, она не нужна

2021-09-19 19:44 UTC, kotosha-real commented on src/components/ui/Toaster/Toast/Toast.tsx
> +    if (toast.timeout) {
❗️
Тут и везде она выглядит лишней

2021-09-21 16:49 UTC, kotosha-real approved these changes
🕵🏻‍♂️
Теперь всё супер!
Ты молодец, правок было много, но ты всё затащила, и это очень круто!

2021-09-21 16:49 UTC, kotosha-real commented on src/components/ui/Toaster/Toast/Toast.tsx
> +  }, [toast.timeout]);
❓
Есть смысл не укзаывать все зависимости?

2021-09-21 16:49 UTC, kotosha-real commented on src/index.tsx
> +import { Toaster } from '@/components/ui';
❗️
Кажется, что тут порядок импортов побился

2021-09-23 08:43 UTC, merged